default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

dev: &dev
  <<: *default
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('DB_HOSTNAME', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

clickhouse: &clickhouse
  migrations_paths: db/clickhouse_migrate
  adapter: clickhouse
  host: <%= ENV.fetch("CLICKHOUSE_HOST", "localhost") %>
  port: <%= ENV.fetch("CLICKHOUSE_PORT", 8123).to_i %>
  username: <%= ENV.fetch("CLICKHOUSE_USER", "default") %>
  password: <%= ENV.fetch("CLICKHOUSE_PASSWORD", "clickhouse") %>

development:
  primary:
    <<: *dev
    database: clickhouse_demo_development
  queue:
    <<: *dev
    migrations_paths: db/queue_migrate
    database: clickhouse_demo_queue_development
  clickhouse:
    <<: *clickhouse
    database: demo_development

test:
  <<: *dev
  database: clickhouse_demo_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    migrations_paths: db/cache_migrate
    url: <%= ENV["CACHE_DATABASE_URL"] %>
  queue:
    <<: *default
    migrations_paths: db/queue_migrate
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
  cable:
    <<: *default
    migrations_paths: db/cable_migrate
    url: <%= ENV["CABLE_DATABASE_URL"] %>
  clickhouse:
    <<: *clickhouse
    database: demo
