# Name of your application. Used to uniquely configure containers.
service: clickhouse-demo

# Name of the container image.
image: clickhouse-demo

# Deploy to these servers.
servers:
  web:
    - clickhousedemo.dev.kg
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

proxy:
  host: clickhousedemo.dev.kg
  forward_headers: true

registry:
  server: registry.dev.kg
  username:
    - DOCKER_REGISTRY_USER
  password:
    - DOCKER_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
  clear:
    CLICKHOUSE_HOST: 172.17.0.1
  secret:
    - CABLE_DATABASE_URL
    - CACHE_DATABASE_URL
    - DATABASE_URL
    - QUEUE_DATABASE_URL
    - SECRET_KEY_BASE

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal app logs -r job" will tail logs from the first server in the job section.
#
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole -p"

# Use a different ssh user than root
#
# ssh:
#   user: app

# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
accessories:
  clickhouse:
    image: clickhouse/clickhouse-server:25.9
    host: clickhousedemo.dev.kg
    options:
      ulimit: nofile=262144:262144
    port:
      - "172.17.0.1:8123:8123"
      - "172.17.0.1:9000:9000"
    env:
      secret:
        - CLICKHOUSE_PASSWORD
    directories:
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_logs:/var/log/clickhouse-server/

#   redis:
#     image: valkey/valkey:8
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data
